IF(NOT KOTIPP_ROOT)
	SET(KOTIPP_ROOT "$ENV{KOTIPP_ROOT}")
ENDIF()
IF(NOT "${KOTIPP_ROOT}" STREQUAL "")
	MESSAGE(STATUS "Searching for Kotipp in ${KOTIPP_ROOT}")
ENDIF()

FIND_PATH(KOTIPP_IMPORT_FILE NAMES cmake-export/kotipp/kotipp.cmake PATHS ${KOTIPP_ROOT})

IF(KOTIPP_IMPORT_FILE)
	INCLUDE(${KOTIPP_IMPORT_FILE})

	IF(NOT KOTIPP_QUIET)
		SET(KOTIPP_LIBRARY $<TARGET_FILE:kotipp_lib>)
		MESSAGE(STATUS "Found Kotipp: ${KOTIPP_LIBRARY}")
	ENDIF()
ELSE()
	IF(KOTIPP_REQUIRED)
		SET(MESSAGE_STATE "FATAL_ERROR")
	ELSE()
		SET(MESSAGE_STATE "STATUS")
	ENDIF()

	SET(MESSAGE_INFO "Could not find Kotipp library. Try setting KOTIPP_ROOT")

	IF(MESSAGE_STATE STREQUAL "STATUS")
		IF (NOT KOTIPP_QUIET)
			MESSAGE(${MESSAGE_STATE} "Could not find Kotipp library. Try setting KOTIPP_ROOT")
		ENDIF()
	ELSEIF(MESSAGE_STATE STREQUAL "FATAL_ERROR")
		MESSAGE(${MESSAGE_STATE} "Could not find Kotipp library. Try setting KOTIPP_ROOT")
	ELSE
		MESSAGE(${MESSAGE_STATE} "Unable to determine message state. This is a developer's problem.")
	ENDIF()
ENDIF()


IF(KOTIPP_LIBRARY)
	IF(KOTIPP_INCLUDE_DIR)
		SET(KOTIPP_FOUND TRUE)
		SET(KOTIPP_LIBRARIES ${KOTIPP_LIBRARY})
		SET(KOTIPP_INCLUDE_DIRS ${KOTIPP_INCLUDE_DIR})
	ENDIF()
ENDIF()

IF(KOTIPP_FOUND)
	MESSAGE(STATUS "Found Kotipp at ${KOTIPP_LIBRARIES}")
ELSE()
	MESSAGE(FATAL_ERROR "Could not find Kotipp library. Try setting KOTIPP_ROOT")
ENDIF()

